name: base
on: [push, pull_request]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - run: yarn run build
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: yarn run lint
  